### ISSUE TITLE
Não to entendendo nada do que ta escrito <o>

### ISSUE THREAD

**Issue by DouglasHennrich** [Webschool-io/workshop-js-funcional-free#3]
Precisa de faculdade pra entender tudo isso que vc escreveu ai? aueheauhae
Sério, não entendi nada, ta difícil uaheuaehuhae =(

**Comment by kurybr** [comment]
Não precisa fazer facul mano ! 

mas entender um pouco de programação é sempre bom, se souber JS melhor ainda ! 
ps: (Matemática tbm vai ajudar eu acho rs )

Mas fica tranquilo, estamos aqui pra ajudar se precisar de algo ;)

:smile:

**Comment by mauricionr** [comment]
Uma hora entende!

**Comment by suissa** [comment]
Bah eu achei que escrevi da forma mais fácil possível ehehhe mas na hora que eu apresentar vai ficar mais simples ;)
