### ISSUE TITLE
Sugestão de inserção de conteúdo importante

### ISSUE THREAD

**Issue by pedropolisenso** [Webschool-io/workshop-js-funcional-free#6]
@suissa lembra que trocamos uma ideia pelo fb sobre conteúdo e tal, uma coisa que não cheguei a ver no README.md foi alguns conceitos da programação funcional como etapa de hosting e IIFE, posso ter passado direto ou não ter visto mesmo, mas se tiver ignore essa issue. A não ser que você aborde isso em uma seção específica que ainda não vi, mas ta valendo!

**Comment by suissa** [comment]
Não viu pq isso nao eh puramente funcional, mas será ensinado sim, valeu a lembrança.

**Comment by pedropolisenso** [comment]
aah pode crer, não é algo para ser um tópico em destaque. Tranquilo
